declare const Utils: {
    eachComponent(components: any, fn: any, includeAll?: boolean | undefined, path?: string | undefined, parent?: any): void;
    guid(): string;
    uniqueName(name: string, template?: string | undefined, evalContext?: any): string;
    keys(obj: any): string[];
    noop(): void;
    each(collection: any, _each: any): void;
    pathParts(path: string): string[];
    get(obj: any, path: string, def?: any): any;
    has(obj: any, path: string): boolean;
    set(obj: any, path: string, value: any): any;
    merge(a: any, b: any, options?: any): unknown;
    fastCloneDeep(obj: any): any;
    defaults(obj: any, defs: any): any;
    isBoolean(value: any): boolean;
    isNil(value: any): boolean;
    isObject(value: any): any;
    findEach(arr: any, query: any, fn: any): void;
    filter(arr: any, fn?: any): any;
    find(arr: any, query?: any): any;
    isEqual(a: any, b: any): boolean;
    pick(object: any, keys?: any): any;
    intersection(a: any, b: any): any;
    trim(str: string, c?: string): string;
    last(arr: any[]): any;
};
export { Utils };
export { Evaluator } from './Evaluator';
export { sanitize } from './sanitize';
export * as dom from './dom';
