export declare function keys(obj: any): string[];
export declare function noop(): void;
export declare function each(collection: any, _each: any): void;
export declare function get(obj: any, path: string, def?: any): any;
export declare function set(obj: any, path: string, value: any): any;
export declare function merge(a: any, b: any, options?: any): unknown;
export declare function fastCloneDeep(obj: any): any;
export declare function defaults(obj: any, defs: any): any;
export declare function isBoolean(value: any): boolean;
export declare function isNil(value: any): boolean;
export declare function isObject(value: any): any;
export declare function intersection(a: any, b: any): any;
export declare function trim(str: string, c?: string): string;
export declare function last(arr: Array<any>): any;
export * from './formUtil';
